# -*- coding: utf-8 -*-
"""connection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zyDosbasCEYMiohi8_znLim6ipV99kOZ
"""

pip install mysql-connector-python

import pandas as pd
import mysql.connector

# Extract: leer datos de una URL
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/airtravel.csv'
df = pd.read_csv(url)

# Transform: realizar algunas operaciones de procesamiento de datos
df['promedio'] = (df[' "1958"'] + df[' "1959"'] + df[' "1960"']) / 3

df = df[df[' "1960"'] > 450]
df = df.dropna()
df = df.rename(columns={' "1958"': 'año 1958', ' "1959"': 'año 1959', ' "1960"': 'año 1960'})
df = df.rename(columns={'Month': 'Mes'})

# Load: establecer conexión con MySQL y cargar los datos en una tabla
conexion = mysql.connector.connect(user='ukq4njegozl8dlkx', password='FhEHCRAwAEzqfzp66njg', host= 'b7au8y7g2g0w7tcvgtut-mysql.services.clever-cloud.com', database='b7au8y7g2g0w7tcvgtut', port= '3306')

# Suponiendo que ya tienes una tabla llamada 'airtravel' creada en tu base de datos
nombre_tabla = 'meses_año'

# Insertar registros del DataFrame en MySQL
with conexion.cursor() as cursor:
    # Crear la tabla si no existe
    crear_tabla_query = '''
    CREATE TABLE IF NOT EXISTS {} (
        Mes VARCHAR(10),
        `1958` INT,
        `1959` INT,
        `1960` INT,
        promedio FLOAT
    );
    '''.format(nombre_tabla)
    cursor.execute(crear_tabla_query)

# Insertar los datos en la tabla
for _, row in df.iterrows():
    insertar_query = '''
    INSERT INTO {} (Mes, `1958`, `1959`, `1960`, promedio)
    VALUES ('{}', {}, {}, {}, {});
    '''.format(nombre_tabla, row['Mes'], row['año 1958'], row['año 1959'], row['año 1960'], row['promedio'])
    with conexion.cursor() as cursor:
        cursor.execute(insertar_query)
    conexion.commit()

# Cerrar la conexión
connection.close()